name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 트리거

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Amazon Corretto JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://apt.corretto.aws/corretto.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
          sudo apt-get update
          sudo apt-get install -y java-17-amazon-corretto-jdk

      - name: Build with Gradle
        run: |
          ./gradlew build -x test
        working-directory: hikingclub

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: hikingclub-jar
          path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: hikingclub-jar

      - name: Verify downloaded file existence
        run: |
          echo "Verifying downloaded file..."
          find ${{ github.workspace }} -name "hikingclub-0.0.1-SNAPSHOT.jar" || echo "File not found"

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          source: "/github/workspace/hikingclub-0.0.1-SNAPSHOT.jar"
          target: "~/hikingclub-0.0.1-SNAPSHOT.jar"
          debug: true
          overwrite: true

      - name: Set permissions on JAR file
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            chmod 600 ~/hikingclub-0.0.1-SNAPSHOT.jar

      - name: Restart application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            pkill -f 'java -jar hikingclub-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar ~/hikingclub-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
