name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amazon Corretto JDK 17
        run: |
          if ! java -version 2>&1 | grep "17.0"; then
            echo "Java 17 is not installed. Installing Amazon Corretto JDK 17..."
            sudo apt-get update
            sudo apt-get install -y wget
            wget -qO- https://apt.corretto.aws/corretto.key | sudo apt-key add -
            sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
            sudo apt-get update
            sudo apt-get install -y java-17-amazon-corretto-jdk
          else
            echo "Java 17 is already installed."
          fi

      - name: Set environment variables for Java
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Java version
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: hikingclub

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: hikingclub
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: List build artifacts
        run: ls -lah hikingclub/build/libs/
        working-directory: ${{ github.workspace }}

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: hikingclub-jar
          path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: hikingclub-jar

      - name: Verify downloaded file existence
        run: |
          echo "Verifying downloaded file..."
          ls -lah hikingclub-0.0.1-SNAPSHOT.jar

      - name: Copy file via SSH
        run: |
          scp -o StrictHostKeyChecking=no hikingclub-0.0.1-SNAPSHOT.jar ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USERNAME }}/hikingclub-0.0.1-SNAPSHOT.jar
