name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Amazon Corretto JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y java-17-amazon-corretto-jdk

      - name: Set environment variables for Java
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: hikingclub

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: hikingclub

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: hikingclub-jar
          path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: hikingclub-jar

      - name: Verify downloaded file existence
        run: |
          echo "Verifying downloaded file..."
          ls -lah hikingclub-0.0.1-SNAPSHOT.jar

      - name: Copy file via SSH
        run: |
          scp -o StrictHostKeyChecking=no hikingclub-0.0.1-SNAPSHOT.jar ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USERNAME }}/hikingclub-0.0.1-SNAPSHOT.jar
