name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amazon Corretto JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://apt.corretto.aws/corretto.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
          sudo apt-get update
          sudo apt-get install -y java-17-amazon-corretto-jdk

      - name: Set environment variables for Java
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto" | sudo tee -a /etc/environment
          echo "PATH=$JAVA_HOME/bin:$PATH" | sudo tee -a /etc/environment
          source /etc/environment

      - name: Verify Java version
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: hikingclub

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: hikingclub
      
      - name: List build artifacts
        run: ls -lah hikingclub/build/libs/
        working-directory: ${{ github.workspace }}

      - name: Archive JAR file
        uses: actions/upload-artifact@v2
        with:
          name: hikingclub-jar
          path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar

      - name: Check file existence
        run: ls -l hikingclub/build/libs/
        working-directory: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: hikingclub-jar

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          source: "${{ github.workspace }}/hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar"
          target: "~/hikingclub-0.0.1-SNAPSHOT.jar"
          debug: true

      - name: Restart application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            pkill -f 'java -jar hikingclub-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar ~/hikingclub-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
