name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amazon Corretto JDK 17
        # 설치 명령은 동일

      - name: Set environment variables for Java
        # 환경 변수 설정은 동일

      - name: Verify Java version
        # Java 버전 확인은 동일

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: hikingclub

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: hikingclub

      - name: List build artifacts
        run: ls -lah hikingclub/build/libs/

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: hikingclub-jar
          path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar

  deploy:
   runs-on: ubuntu-latest
   needs: build

   steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: hikingclub-jar

    - name: Verify downloaded file existence
      run: find ${{ github.workspace }} -name "hikingclub-0.0.1-SNAPSHOT.jar" || echo "File not found"

    - name: Copy file via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        source: "${{ github.workspace }}/hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar"
        target: "~/hikingclub-0.0.1-SNAPSHOT.jar"
        debug: true
        overwrite: true

    - name: Restart application
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          pkill -f 'java -jar hikingclub-0.0.1-SNAPSHOT.jar' || true
          nohup java -jar ~/hikingclub-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
