name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'corretto'  # AWS Corretto JDK 사용

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Archive JAR file
      uses: actions/upload-artifact@v2
      with:
        name: hikingclub-jar
        path: build/libs/hikingclub-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: hikingclub-jar

    - name: Copy file via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        source: "hikingclub-0.0.1-SNAPSHOT.jar"
        target: "~/hikingclub-0.0.1-SNAPSHOT.jar"

    - name: Restart application
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          pkill -f 'java -jar hikingclub-0.0.1-SNAPSHOT.jar' || true
          nohup java -jar ~/hikingclub-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
